### PR TITLE
don't rely on the full path anymore for more flexibility

### PR DESCRIPTION
**Pull request by xmunoz**
@timwis Can you help me test that everything still works? Also, is there anything you would add/change/remove?

### CODE REVIEW

**Comment by timwis** [comment]
Sure thing - I'll take a poke this week. At first glance though I thought it's worth considering removing `.json` while you're at it. Perhaps json could be the default content type unless a `content_type` kwarg is passed? Just a thought

**Comment by chrismetcalf** [comment]
Looks like you've adopted a similar model to the one that I use for the https://github.com/socrata/soda-ruby library?

**Comment by xmunoz** [comment]
@chrismetcalf: totally a coincidence, but I'm glad it worked out that way. Great minds think alike? Also, @timwis, I like that idea. If I make that change though, I'm not going to preserve any backwards compatibility because it will be too annoying. I'll add validation though and update the readme to reflect the change.

**Comment by xmunoz** [comment]
@timwis, maybe hold off on testing then until I get those new changes in

**Comment by timwis** [comment]
Sounds good!

**Comment by xmunoz** [comment]
Gah! Finally ready for a test. Do your worst @timwis.

**Comment by timwis** [comment]
Hopefully I did this right, but I just made a [pull request](https://github.com/xmunoz/sodapy/pull/11) on your pull request :P. Found a typo and what I assume was unintentional strings in your `.format()` params and put those in the string itself. The only other thing I'd draw attention to is that in `test_soda.py`, the const `PATH` at the top isn't really a path anymore, so a different variable name (like dataset_identifier for consistency) may make sense. Obvious that's just for readability. I tested creating, publishing, setting permissions, and deleting. Nice work!

**Pull request merged**
