### PR TITLE
Python 2 and 3 compatibility 

### PR DESCRIPTION
**Pull request by MrKriss**
I've added Python 3 compatibility to existing code using [python-future](http://python-future.org/), and so it should now run on both Python 2 and 3.

### CODE REVIEW

**Comment by MrKriss** [comment]
Ok, so this is currently failing to build on Travis CI with Python 2. I'll investigate further soon, it's likely that `future` will need to be added to requirements.txt

**Comment by xmunoz** [comment]
Can you update .travis.yml to test python3 also? This might require some changes to the tests too...

**Comment by MrKriss** [comment]
Tests already converted so all should be good now.

**Comment by xmunoz** [comment]
Thanks for the PR. Unfortunately, I pushed this without adequate testing and it looks like the local environment needs to have the `future` module globally installed in order to build `sodapy`. I'm going to move all of these exciting compatibility changes out of master and into a separate branch for now, and further meditate on how to accommodate python3 (probably a separate package, sodapy3?). I'm open to ideas here though.

**Pull request merged**
