### PR TITLE
Example basic queries

### PR DESCRIPTION
**Pull request by matthewwritter**
* Added a Jupyter notebook going through two use cases, along with a .py version of the same.
* Made a slight tweak to the __init__ method to strip urls to the format that the code expects (which tripped me up for a while). I know that this is overstepping the original mandate, so feel free to remove.

I tried running the tests but was unable to:

```
(sodapy) [19:43:23] sodapy $ run_tests.py tests/
Traceback (most recent call last):
  File "/usr/local/bin/run_tests.py", line 22, in <module>
    import cStringIO
ModuleNotFoundError: No module named 'cStringIO'
```
Attempts to pip install cStringIO and StringIO were unsuccessful - any pointers on how I can move forward on that?

### CODE REVIEW

**Comment by xmunoz** [comment]
> Attempts to pip install cStringIO and StringIO were unsuccessful - any pointers on how I can move forward on that?

Those are python built-ins. Any needed requirements should be in the requirements file. Also, I need to update the readme, because runnings the tests involves just running `pytest`. I'll take a closer look at the PR when the build is green.

**Comment by matthewwritter** [comment]
OK, made the updates to get everything green!

**Comment by matthewwritter** [comment]
Done and done!

**Comment by xmunoz** [comment]
Fixes #41

**Pull request merged**
